### ISSUE TITLE
[Bug?] Rounded Border issue for custom nitro profiles

### ISSUE THREAD

**Issue by xendak** [refact0r/midnight-discord#105]
Left bottom border is the only flat border for some reason

![image](https://github.com/refact0r/midnight-discord/assets/108767275/7a1c2d3c-25dc-48f0-9168-f0de3ef0c22e)

i never really paid attention to this, but since i changed the background to something a bit darker now its a bit more apparent? idk since when this began, it only happens with custom profiles for other people though :)

**Comment by refact0r** [comment]
fixed at some point
