### ISSUE TITLE
Discord Updated the Random Classes again....

### ISSUE THREAD

**Issue by barraIhsan** [refact0r/midnight-discord#106]
![image](https://github.com/refact0r/midnight-discord/assets/57800056/9d50113c-4114-494c-b72e-ce78020b1948)
for example,
```
.privateChannels__9b518 /* dms list */,
```
become
```
.privateChannels__f0963d /* dms list */,
```

Is there like, a way to select it without the random class? So it doesn't need to update the class every discord update? (using aria-label or smthing)

**Comment by Neodyminus** [comment]
Yep same here. lots broken. 
Red "new message line"
Inbox button different position/theme
this harsh change between main view and the DM's list (same with servers/channels)
![image](https://github.com/refact0r/midnight-discord/assets/113160559/63687eb0-7ca9-4bdd-b080-551ac3ab7c77)


why does discord have to change things 😢

**Comment by barraIhsan** [comment]
> why does discord have to change things 😢

because they use js framework that produce random classes each time? CMIIW

**Comment by FilipeGiesta** [comment]
The classes fix does not fix the rounded stuff

**Comment by MagmaBro123** [comment]
Please update.

**Comment by refact0r** [comment]
fixed
