### ISSUE TITLE
Hovering over new quest notification doesn't allow you to read the information.

### ISSUE THREAD

**Issue by banthab0mb** [refact0r/midnight-discord#112]
When I hover over the new quest notification, the information does not leave the box and I cannot read it. 

https://github.com/refact0r/midnight-discord/assets/174663218/933b8553-414a-4ee1-8e12-d65529187317

**Comment by refact0r** [comment]
unless they start pushing these all the time, i don't intend to support one-time popups like this. its just not feasible, how am i supposed to get the popup again? steal someone's account?

just temporarily turn off the theme to read it.
