### ISSUE TITLE
Is there a way to adjust the roundness of these? (CLOSED)

### ISSUE THREAD

**Issue by Revonlieke** [refact0r/midnight-discord#127]
![image](https://github.com/user-attachments/assets/9da6420b-546b-457e-b312-14bcdb466a58)

![image](https://github.com/user-attachments/assets/d3ed3367-9ae9-42b6-8dff-7e972374ba26)

Is there a way to adjust the roundness of these?
1. The hover over roundness on the username. (blue area)
2. The background color roundness of "online", "set custom status" and "switch accounts"
(If you make --roundness-m: larger than 8px, the background color roundness wont adjust in the profile card)
3. the roundness of the users on the server

Thanks a bunch.

**Comment by H4TK1D** [comment]
1. Use the class `avatarWrapper_b2ca13`
2. I'm not sure what you mean here
3.  Try with the class `layout_d808b0`

**Comment by Revonlieke** [comment]
Got it working days ago. Thanks!
