### ISSUE TITLE
Fix HSL compatibility

### ISSUE THREAD

**Issue by DarkblooM-IO** [refact0r/midnight-discord#129]
Is it possible to fix the display the server list when using [Horizontal Server List](https://github.com/DiscordStyles/HorizontalServerList)? Right now the rightmost end of the list sticks to the edge of the window and is not rounded (see screenshot).  

![image](https://github.com/user-attachments/assets/8b27124e-f172-47d8-931b-c9e5e5a1c2c3)

**Comment by H4TK1D** [comment]
HSL has a hardcoded width that can't be overridden without breaking midnights default theme. I made an external theme that patches it though, if you want to use it. Just install it like any other theme.

[hslxmidnight.zip](https://github.com/user-attachments/files/17180728/hslxmidnight.zip)

**Comment by DarkblooM-IO** [comment]
Awesome, tysm
