### ISSUE TITLE
area around discover button looks wonky?

### ISSUE THREAD

**Issue by starling0526** [refact0r/midnight-discord#139]
i'm by no means good at coding nor am i too tech savvy etc., but i use biscuit for my discord theme with the colors altered to my own liking for customization so that it's easier on my eyes as dark mode on pc isn't dark enough for me. i've noticed, however, that it seems to be a little bugged or something, as in the bottom right corner, the area surrounding the discover button is blending into the spacing and secondary elements, making it look a little off compared to the rest of my screen.

as you can see in my screenshots, i altered the color in my settings to try and figure out if i could identify where the color was from and work from there, and when i changed the bg-3 hex i was able to see that the area surrounding the discover button was bleeding into the spacing.

<img width="83" alt="Screenshot 2024-10-03 at 14 13 21" src="https://github.com/user-attachments/assets/d0fe3055-af96-4211-924c-bee60420dab5">
<img width="546" alt="Screenshot 2024-10-03 at 14 13 31" src="https://github.com/user-attachments/assets/b85786c8-541e-48f7-9f6d-20b64be293a6">
<img width="621" alt="Screenshot 2024-10-03 at 14 15 33" src="https://github.com/user-attachments/assets/7fc44b19-c985-4ede-bbeb-3025065f58c2">
<img width="82" alt="Screenshot 2024-10-03 at 14 15 39" src="https://github.com/user-attachments/assets/b15cec18-0c40-439c-85cc-5e6f878aff2e">

**Comment by H4TK1D** [comment]
This should be fixed if and when #138 is merged

**Comment by H4TK1D** [comment]
It has been merged, should be fixed once you update

**Comment by Viren070** [comment]
its still weird, I've used the link to install it. 

![image](https://github.com/user-attachments/assets/46b20943-0f6e-4d2f-96f0-7a7b024e5630)

![image](https://github.com/user-attachments/assets/1fa1215e-8b17-49c7-9fbd-26b7cfd79c76)

**Comment by H4TK1D** [comment]
I see what you mean, will try to fix it again

**Comment by H4TK1D** [comment]
#152 Should re-fix it, they changed the footer class so that's why it broke

**Comment by Viren070** [comment]
Thanks. I tested it out and it looks fixed now. 
![image](https://github.com/user-attachments/assets/aacc13b2-0eb7-4fd2-9dff-06527458219c)
![image](https://github.com/user-attachments/assets/0fb17241-9172-4dfa-b9e4-0326691adc29)
