### ISSUE TITLE
Server joining or creation menu is not themed

### ISSUE THREAD

**Issue by he3als** [refact0r/midnight-discord#14]
![image](https://user-images.githubusercontent.com/65787561/227808007-14c052e7-b230-4cd6-973c-a8a571787e51.png)

**Comment by refact0r** [comment]
Not perfect but should be fixed by https://github.com/refact0r/midnight-discord/commit/30a8e836cc18ae4147f7f210668b6e94476e8c54 for now

**Comment by piotr25691** [comment]
> Not perfect but should be fixed by [30a8e83](https://github.com/refact0r/midnight-discord/commit/30a8e836cc18ae4147f7f210668b6e94476e8c54) for now

still in light theme however i could make a pull request to fix it

**Comment by refact0r** [comment]
Yeah it broke again so I decided to just not theme it in the last update, as you barely ever see it. If you want you can make a pr but I don't intend to fix it.
