### ISSUE TITLE
Incorrect rounded borders for the members list

### ISSUE THREAD

**Issue by MitchelMA** [refact0r/midnight-discord#141]
Bottom-left corner of the members list not rounded:
![image](https://github.com/user-attachments/assets/8252442e-4793-4671-aaed-ac92f0ec852e)

Possible solution:
![image](https://github.com/user-attachments/assets/6904853d-e19d-40ab-848f-ceed19235b7e)

(This is for vencord)

**Comment by H4TK1D** [comment]
PR has been opened with a fix #142
