### ISSUE TITLE
Discord bar

### ISSUE THREAD

**Issue by Deykii** [refact0r/midnight-discord#146]
I like this theme, but MacOs styled bar is not comfortable fofr me. Is there a way to make it look more like windows? 
I found "Configurable nav button style (Styled / Windows) #145", but I didn't understand how to recreate this, sorry =(

**Comment by H4TK1D** [comment]
Hello there!
To customize the bar like in #145, just go to whichever theme of midnight you may be using and you should see this section:
![Image](https://github.com/user-attachments/assets/716aff5b-d2b6-40e4-8dde-d3fd328f87b6)
Just change "--windows-nav" to block and "--custom-nav" to none and that should give you the windows control buttons back, if there's more let me know

**Comment by Deykii** [comment]
> Hello there! To customize the bar like in #145, just go to whichever theme of midnight you may be using and you should see this section: ![Image](https://private-user-images.githubusercontent.com/116733883/390189137-716aff5b-d2b6-40e4-8dde-d3fd328f87b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3NjkwODksIm5iZiI6MTczMjc2ODc4OSwicGF0aCI6Ii8xMTY3MzM4ODMvMzkwMTg5MTM3LTcxNmFmZjViLWQyYjYtNDBlNC04ZGRlLWQzZmQzMjhmODdiNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOFQwNDM5NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZTI2MmJlZTRkOTdmY2Q1YWUxNzU3OTUzMzkzNjdkNGY4YjZhODc1Mjg0OGZjMzMzMTljMjI0MTU3YTc5ZDI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.5zaJlv7HS-y9FYWaFnJuVn3NjfwTw5t7BB4vgEBomzM) Just change "--windows-nav" to block and "--custom-nav" to none and that should give you the windows control buttons back, if there's more let me know

Uuhhh... I can't find it...
![image](https://github.com/user-attachments/assets/f1366036-819a-4133-a16f-e9ebd054056c)

**Comment by refact0r** [comment]
> Uuhhh... I can't find it...

Redownload the theme file from github.

**Comment by Deykii** [comment]
> > Uuhhh... I can't find it...
> 
> Redownload the theme file from github.

Thanks!!!
