### ISSUE TITLE
Top Bar Display Issue

### ISSUE THREAD

**Issue by valxe** [refact0r/midnight-discord#147]
The top bar (or whatever the element in my image is called) is not displaying correctly when using this custom CSS. I’ve tested it without any CSS and with other styles, and it displays correctly in those cases.

![{BCDDBD15-1D7C-41D5-ACEE-B18FF0B1DDB5}](https://github.com/user-attachments/assets/7cdbaecf-9229-48cb-82b5-f43ecdafb68f)

**Comment by H4TK1D** [comment]
@refact0r most likely has to fix this themself as discord updated their design and this might require a design change as well. The way it worked before was by discord splitting the toolbar and search like with server member lists, but now that they've gone back on that and kept the header the same no matter if you have the profile open or not, it won't move automatically anymore and split.

**Comment by Suburbanno** [comment]
same here
