### ISSUE TITLE
Embeds not showing embed color on the side

### ISSUE THREAD

**Issue by aisukuma** [refact0r/midnight-discord#16]
A Discord update probably broke something with embed colors

With current version of midnight (1.4.0)
![image](https://user-images.githubusercontent.com/22802219/230141538-c413b6e3-4f2d-4b22-90f1-172ea9af0186.png)

Without midnight theme
![image](https://user-images.githubusercontent.com/22802219/230141866-9252ea5d-ca52-4749-92d3-98cf5c669217.png)

**Comment by refact0r** [comment]
This is intended for default color embeds. Does it happen on other colors as well?

**Comment by aisukuma** [comment]
Yes

Theme disabled: 
![image](https://user-images.githubusercontent.com/22802219/230237383-0bcfac06-1b8e-4ab9-8774-702ccf330cd9.png)

Theme enabled:
![image](https://user-images.githubusercontent.com/22802219/230237446-0ded6f2f-9aae-4a40-bc69-a04ae4f857f5.png)

**Comment by refact0r** [comment]
fixed in https://github.com/refact0r/midnight-discord/commit/41f0119bc34a9fedc6a087aeeed8c6045deb5a4b
