### ISSUE TITLE
Images got cut off

### ISSUE THREAD

**Issue by nhan000** [refact0r/midnight-discord#17]
what it should look like 
![image](https://github.com/refact0r/midnight-discord/assets/85216095/eaf4fb49-e0fb-4dc7-ae47-93a3155a3053)

you can see the top part got cut off (I'm using Stylus extension)
![image](https://github.com/refact0r/midnight-discord/assets/85216095/2e5bff6f-ac96-4692-bd91-47c0ccdff5a8)

**Comment by refact0r** [comment]
I must've accidentally marked this as read, is this still an issue?

**Comment by nhan000** [comment]
sorry it was buggy so I stopped using it.

**Comment by refact0r** [comment]
I just tried the theme with Stylus and it seems like this does not happen anymore.
