### ISSUE TITLE
Custom CSS no longer applying

### ISSUE THREAD

**Issue by DanielMoisei** [refact0r/midnight-discord#18]
Worked fine last night and in the morning when I started the app it reverted to default styling, completely ignoring changes. 
Stuff tried:
- Changing colors at random, nothing applies at all
- Uninstalling the theme and reinstalling it
- Reinstalling BetterDiscord

Just to clarify I'm talking about changing colors within the theme's file, not custom CSS outside of it.

**Comment by k4tana9** [comment]
this happened to me 
i think its because of the new update pushed to github that broke the css override for the theme

**Comment by franz-dc** [comment]
It seems that v1.5 is not yet on BetterDiscord. In the meantime, you can edit the theme and change

```css
@import url('https://refact0r.github.io/midnight-discord/midnight.css');
```
to
```css
@import url('https://refact0r.github.io/midnight-discord/midnight-old.css');
```

if you don't want to change the variables from your custom theme.

I'd rather suggest changing your custom theme variables to support newer versions of midnight moving forward.
You can refer to the changed variables [here](https://github.com/refact0r/midnight-discord/blob/master/midnight.theme.css) for now.

**Comment by k4tana9** [comment]
Thanks for the help, changing the link worked. 
By changing the custom theme variables, do you mean that I should go into the theme file and change them directly?

**Comment by franz-dc** [comment]
Sorry for the confusion. I meant going to your custom CSS and changing the old variables to new ones.

**Comment by k4tana9** [comment]
oh right ok

**Comment by refact0r** [comment]
@DanielMoisei @k4tana9 
Sorry for the sudden change, I changed the variable names to make them easier for me to read and forgot that it would break everyone's customizations. I will not update the old versions going forward, so make sure you update/redownload your midnight.theme.css file to get the new variables. You can customize from there.
