### ISSUE TITLE
message search looks good in servers but bad in dms due to extra "show user profile" button

### ISSUE THREAD

**Issue by Dev-Egor** [refact0r/midnight-discord#19]
![image](https://github.com/refact0r/midnight-discord/assets/90320659/7dd049d7-972d-4f00-85ae-480abad7a737)
![image](https://github.com/refact0r/midnight-discord/assets/90320659/2ae12c8a-eb11-412b-956f-9ed96f0db22f)
also looks bad with vencord toolbox button.

**Comment by refact0r** [comment]
Just wondering, was this broken by the update yesterday or was it always a problem?

**Comment by refact0r** [comment]
Ok, I will try to fix soon. 
The header bar is especially annoying with this theme because they change on different pages.

**Comment by refact0r** [comment]
Another thing, what is the vencord toolbox button? (I am using vencord)

**Comment by refact0r** [comment]
I have pushed a fix, please verify that the issue is resolved.
