### ISSUE TITLE
Non-classic theme not round.

### ISSUE THREAD

**Issue by shikeishu** [refact0r/midnight-discord#2]
The BD site preview shows that it should be fine, but in my client it isn't round. Classic looks the same but with slightly different colors

I am on BD on regular Discord. 

![ ](https://cdn.discordapp.com/attachments/878698871415537726/930326479110287380/unknown.png)

Note: Some of my other themes are also not working properly so maybe on my end?

**Comment by refact0r** [comment]
It's probably because discord recently had an update which changed a lot of css classes. I will try fixing this soon.

**Comment by refact0r** [comment]
Alright should be fixed now.
