### ISSUE TITLE
theme color no longer changes

### ISSUE THREAD

**Issue by kaqur677** [refact0r/midnight-discord#20]
Yesterday everything was fine, I had a pink discord theme. I went in this morning and the color does not change anymore, it remains blue even after changing the color directly in the code

**Comment by refact0r** [comment]
Yeah sorry, I changed the color variable names. I assume by pink/blue you mean the accent colors on unread indicators. Make sure to update your `midnight.theme.css` file and you should be able to change the `--accent-x` variables.

**Comment by kaqur677** [comment]
thanks! i will try
