### ISSUE TITLE
Font color is inconsistent on profiles. 

### ISSUE THREAD

**Issue by makimwah** [refact0r/midnight-discord#28]
Font colors are very washed out when viewing a profile. Looks fine when only tapping on the avatar, so I'm assuming this is not the way it's meant to be.  
![image](https://github.com/refact0r/midnight-discord/assets/142122782/f2d1fbd6-46d3-45b4-b31e-62cf43ef0f75)
![image](https://github.com/refact0r/midnight-discord/assets/142122782/6ea32e0b-3cd8-4a75-b5a2-b1a4c4d3ea5f)

**Comment by refact0r** [comment]
ugh discord moment, they really can't make anything in their app consistent.

**Comment by refact0r** [comment]
I know it doesn't look great, but I don't have a good solution to this right now. I can't manually set all the text to a darker color because for some reason it's also applied on dark backgrounds.

**Comment by makimwah** [comment]
Feel like adding that this also applies to tapping the profile on midnight-old.css.
![image](https://github.com/refact0r/midnight-discord/assets/142122782/e7060a2a-e66d-435c-b03f-71f06d773571)

**Comment by refact0r** [comment]
Don't use midnight-old, it's an older version that is pretty much worse in every way and won't be updated.

**Comment by makimwah** [comment]
I see. Thought it might give you a clue since it is partially fixed on the updated version.

**Comment by refact0r** [comment]
seems like this is fixed after the latest discord update?

**Comment by makimwah** [comment]
I don't know what exactly you've (or Discord) has changed but yes it seems to be fixed. Thank you. 
![image](https://github.com/refact0r/midnight-discord/assets/142122782/0f4eafc7-e6ac-4839-945f-0f9fafa7cf4e)
![image](https://github.com/refact0r/midnight-discord/assets/142122782/14e5a9bb-1926-4c7c-ad60-d235d22108f1)

**Comment by refact0r** [comment]
Not me, discord just fixed their colors lol
