### ISSUE TITLE
online indicator

### ISSUE THREAD

**Issue by Dev-Egor** [refact0r/midnight-discord#29]
![image](https://github.com/refact0r/midnight-discord/assets/90320659/d5a90efa-d32b-48d7-8e6e-fa86d2c0fb53)
scuffed blue square is scuffed

**Comment by refact0r** [comment]
damn

**Comment by refact0r** [comment]
what client?

**Comment by refact0r** [comment]
i updated it today but apparently i broke it

**Comment by refact0r** [comment]
Just pushed a fix, can you check to see if it works?
