### ISSUE TITLE
Glowing

### ISSUE THREAD

**Issue by Spudsickle** [refact0r/midnight-discord#3]
The "New Message" bar, mention "strip", and so are the dots to the left of the servers to indicate if you're on the server are glowing. If it was intentional, is there a way to remove it? Note: I did customize colors

![image](https://user-images.githubusercontent.com/92220155/161446933-fca6f6b6-efca-4a6c-a9a2-33b1db6cfee0.png)

![image](https://user-images.githubusercontent.com/92220155/161446964-8fd776bf-b3d0-4fc5-8ee2-398228f610e8.png)

![image_2022-04-03_132116](https://user-images.githubusercontent.com/92220155/161446878-d66f1348-8155-4f9f-8fc8-aa2866b63e3a.png)

**Comment by refact0r** [comment]
Yes, this is intentional. I have pushed an update that allows you to change the amount or remove the glow. When BetterDiscord approves it you should see it in your theme file.
