### ISSUE TITLE
Rounding and top bar

### ISSUE THREAD

**Issue by Dev-Egor** [refact0r/midnight-discord#31]
Rounding missing, server and DMs top message search bar broken, very weird
![image](https://github.com/refact0r/midnight-discord/assets/90320659/2016a32d-2bc0-4e43-b105-b9ffbe3acf4b)
![image](https://github.com/refact0r/midnight-discord/assets/90320659/d3112a18-2616-414d-9804-eddbd194b12d)

**Comment by refact0r** [comment]
Why did you close? Anyways I have already fixed and will push soon.

**Comment by refact0r** [comment]
ohhhhh i forgot that was you on discord
