### ISSUE TITLE
Theme no longer applies correctly. 

### ISSUE THREAD

**Issue by makimwah** [refact0r/midnight-discord#32]
Built config changed for better optimization. Theme no longer applies correctly tho. 
![image](https://github.com/refact0r/midnight-discord/assets/142122782/98caf29e-d3e9-4f59-b6fd-7da47c991949)

**Comment by refact0r** [comment]
i have pushed a temporary fix with a rewrite of the barebones theme. i will add details and more fixes later.

**Comment by piotr25691** [comment]
> i have pushed a temporary fix with a rewrite of the barebones theme. i will add details and more fixes later.
> 
> note: discord just rehashed the classes a second time, so i wrote this fix based on ptb. the fixes might take a while to show up on stable discord.

this appears to be appearing correctly on vencord web on firefox, but dorion doesn't do that (it's a different web client mod with vencord)

**Comment by refact0r** [comment]
> dorion doesn't do that (it's a different web client mod with vencord)
i don't know anything about dorion but i assume it'll get the update too eventually. there's nothing about the theme that would make it not work on certain clients (and if it doesn't work on a certain client, that client is bad and i will not support it).

**Comment by piotr25691** [comment]
> > dorion doesn't do that (it's a different web client mod with vencord)
> 
> i don't know anything about dorion but i assume it'll get the update too eventually. there's nothing about the theme that would make it not work on certain clients (and if it doesn't work on a certain client, that client is bad and i will not support it).

it will most likely work, it already has partially applied on my instance of dorion

![obraz](https://github.com/refact0r/midnight-discord/assets/71488561/e12c0d09-fda7-4779-83a6-7add532e830e)

**Comment by refact0r** [comment]
weird, colors should apply no matter what, but other things should depend on the classnames and updates. i guess they're still on an old build of discord?

**Comment by refact0r** [comment]
Ok the theme should mostly be back, there are probably some small things I missed, please make new issues for those. I will close this issue once someone verifies it works.

**Comment by piotr25691** [comment]
> weird, colors should apply no matter what, but other things should depend on the classnames and updates. i guess they're still on an old build of discord?

what's more confusing is that the theme works fine under vencord web for chrome/firefox, but not quite on the other client that clearly is using the same client and mostly the same vencord (a fork)

**Comment by makimwah** [comment]
> Ok the theme should mostly be back, there are probably some small things I missed, please make new issues for those. I will close this issue once someone verifies it works.

There's a couple of stuff I'm immediately noticing but the overall theme is there and looks the same on stable and canary. I'll make a single issue containing inconsistencies I notice instead of just spamming you with issue tickets, unless you don't want that. 
![image](https://github.com/refact0r/midnight-discord/assets/142122782/29e7ed6d-a0c6-4511-bbd1-550d950cc1f2)
