### ISSUE TITLE
Accent colour does not apply to mentions and channel links properly

### ISSUE THREAD

**Issue by SuperIronMan987** [refact0r/midnight-discord#33]
I copied the default midnight.theme.css and set all accent colours to red to make this more obvious
It looks like this when not hovered
![image](https://github.com/refact0r/midnight-discord/assets/70151481/7f880455-84ee-48d9-a01d-210ee38d5975)

But applies correctly when hovered
![image](https://github.com/refact0r/midnight-discord/assets/70151481/2edc67a4-ffa7-4b9a-9f04-64e0d0da8fec)

**Comment by SuperIronMan987** [comment]
I am on vencord for discord canary if thats relevant

**Comment by refact0r** [comment]
yep i forgot to set mention-foreground. fix coming soon.

**Comment by refact0r** [comment]
fixed
