### ISSUE TITLE
Unstabble CPU Usage

### ISSUE THREAD

**Issue by AnviIndo** [refact0r/midnight-discord#34]
when aplying this themes, after that when write something on chat bar, sudenly my cpu usage raising into 30-50% sometimes into 80-90% make my discord lagging so hard, while i am take off the themes, the problem is gone. (look at bottom right, at electric emote, thats cpu usage)
![image](https://github.com/refact0r/midnight-discord/assets/88024047/a68ccd0b-4582-477e-afc2-1393f4e6521a)
![image](https://github.com/refact0r/midnight-discord/assets/88024047/1d77216f-5b9d-458f-95b0-89de15fd18ae)

**Comment by refact0r** [comment]
i was afraid this would happen. there's 3 sections of code that use `:has(something)`. can you delete those parts and see if the performance is still bad?

**Comment by AnviIndo** [comment]
> i was afraid this would happen. there's 3 sections of code that use `:has(something)`. can you delete those parts and see if the performance is still bad?

i cant, because thats part on the core of your themes right ? at midnight.css

**Comment by AnviIndo** [comment]
> i was afraid this would happen. there's 3 sections of code that use `:has(something)`. can you delete those parts and see if the performance is still bad?

oh yeah bruh, the problem at there, after i remvoe it, the problem is gone

**Comment by AnviIndo** [comment]
ah yes, another one ig, when do slash command, the list of command section still vanilla, is this intentional ? 
![image](https://github.com/refact0r/midnight-discord/assets/88024047/e0444228-3660-4850-a4ee-ff888d0d73b8)

**Comment by refact0r** [comment]
> ah yes, another one ig, when do slash command, the list of command section still vanilla, is this intentional ?

I am still working on fixing stuff like this.

**Comment by refact0r** [comment]
> oh yeah bruh, the problem at there, after i remvoe it, the problem is gone but the icon placement at upper right look funny now 

Ok, I will try to find a way to replace those lines. It might not be possible without using aria-labels, which I want to avoid because they are language specific.

**Comment by refact0r** [comment]
@AnviIndo I have pushed a fix that slightly modifies the problematic :has() selectors. Could you update your theme and test the performance again?

**Comment by AnviIndo** [comment]
> @AnviIndo I have pushed a fix that slightly modifies the problematic :has() selectors. Could you update your theme and test the performance again?

@refact0r ah alr, the problem has been fixed, ty for your hardwork 👍
