### ISSUE TITLE
Overview of broken theme elements after rehash. 

### ISSUE THREAD

**Issue by makimwah** [refact0r/midnight-discord#35]
Instead of creating 12 new issues, I will create a single one with some issues and inconsistencies as to not spam you full of tickets. Screenshots attached obviously so you'll have a broad idea of the issues. 

1. The server list now has a very unfitting and ugly bar.
![image](https://github.com/refact0r/midnight-discord/assets/142122782/51d77355-8cbb-4e69-8dd7-e894c6967204)

2. Color overwrite only applies when hovering. 
![image](https://github.com/refact0r/midnight-discord/assets/142122782/181731f4-405e-4f55-b169-454cd22cc2e1)

3. Color overwrite no longer applied to folders. 
![image](https://github.com/refact0r/midnight-discord/assets/142122782/58f1d623-f199-4f29-83af-b5740e8fcc00)

4. Color overwrite no longer applies to create + find server button. 
![image](https://github.com/refact0r/midnight-discord/assets/142122782/86ab477e-0d86-4fd4-8127-730918e476bd)

5. Color overwrite no longer applies to the add friend button. 
![image](https://github.com/refact0r/midnight-discord/assets/142122782/3b244fb3-4cd2-467b-8dce-f2c1c7b276a2)

6. Color overwrite no longer applies to online status. 
![image](https://github.com/refact0r/midnight-discord/assets/142122782/03e04ee2-cd62-4165-a5aa-db9d49cb95a1)

7. Color overwrite no longer applies to "Voice Connected"
![image](https://github.com/refact0r/midnight-discord/assets/142122782/18e41ec9-7404-4715-a46d-67ac3f6aef1d)

8. Default theming clashes with midnight theme when deleting a message, making the date unreadable. 
![image](https://github.com/refact0r/midnight-discord/assets/142122782/9776fb92-52aa-4208-b53f-73c60a468b03)

9. Text color applies to "start an activity" button. Horrible contrast, makes it unreadable. 
![image](https://github.com/refact0r/midnight-discord/assets/142122782/cd5f516e-077f-4d26-bc3d-b8316366efa9)

10. Old bordering bug in fullscreen mode when calling returned. 
![image](https://github.com/refact0r/midnight-discord/assets/142122782/087b9598-3c1b-49fd-91e7-962758dea8c7)

11. Join Voice button no longer color overwritten (not sure if that was the case before the rehash either but it's just something I noticed)
![image](https://github.com/refact0r/midnight-discord/assets/142122782/af3bb656-816c-4e0d-9462-dae29bf398bc)

12. Delete button is color overwritten, but only when you're not hovering. Hover over it and it will become red. 
![image](https://github.com/refact0r/midnight-discord/assets/142122782/68808823-2ae4-4044-a6ac-500a0d6bd8e4)
![image](https://github.com/refact0r/midnight-discord/assets/142122782/189e2c6c-fe44-40d0-87d4-24aa9a08cb60)

13. Scroll wheel is missing in the menu. 
![image](https://github.com/refact0r/midnight-discord/assets/142122782/3bb818de-2e9d-46ad-8c27-06eda6644321)

**Comment by refact0r** [comment]
#1 is intentional. I wasn't sure if people would like it but I thought it looked a bit more consistent. Is it really that bad?

I will keep working on color override fixes, those  are just manual additions. Thanks for showing me all these.

**Comment by refact0r** [comment]
What exactly does #10 mean?

**Comment by makimwah** [comment]
> What exactly does #10 mean?

When in a call, full screen mode has a rounded border. Here's an example of Discord running without any theme. Compare the theme and unthemed borders. 
![image](https://github.com/refact0r/midnight-discord/assets/142122782/6931a003-01c3-4770-8447-ce2ad4bd71d3)
![image](https://github.com/refact0r/midnight-discord/assets/142122782/abb135bd-0521-4ad3-a0c3-ae07222d6a26)

**Comment by makimwah** [comment]
> #1 is intentional. I wasn't sure if people would like it but I thought it looked a bit more consistent. Is it really that bad?
> 
> I will keep working on color override fixes, those are just manual additions. Thanks for showing me all these.

I think it looks really poor, simply because i liked how it previously matched well together with the window bar, like in the vanilla theme. 
![image](https://github.com/refact0r/midnight-discord/assets/142122782/86a0f64d-d63d-4900-873e-d568af047b6d)

**Comment by refact0r** [comment]
> When in a call, full screen mode has a rounded border. The first screenshot is Discord themed, the second is vanilla. Compare the theme and unthemed borders. 

I'll have to look into this. It might not be possible to hide the border without using more :has() selectors, which are terrible for performance (see #34). I honestly don't mind it too much.

**Comment by makimwah** [comment]
> > When in a call, full screen mode has a rounded border. The first screenshot is Discord themed, the second is vanilla. Compare the theme and unthemed borders.
> 
> I'll have to look into this. It might not be possible to hide the border without using more :has() selectors, which are terrible for performance (see #34). I honestly don't mind it too much.

Yeah, it's not that bad, but it used to be fixed so I just pointed out.

**Comment by refact0r** [comment]
issue #9 is different though. i think the borders existed, but were inconsistent in size.

**Comment by refact0r** [comment]
2, 3, 8, 12, and 13 fixed. 

10 is not really a problem, it not be changed because I don't want to have to use more `:has()` selectors. I'm pretty sure it has been like that for the past few months anyway. 

I sorta like how 1 is right now. I'll keep it for now until more people complain about it. If you hate it you can remove the `/* separate guilds panel */` section in the code.

**Comment by makimwah** [comment]
With BetterFolders now fixed, it creates a second server bar when you're dropping the folder down that almost looks like it's overlapping other UI elements.  
![image](https://github.com/refact0r/midnight-discord/assets/142122782/4effe9ff-8582-4f94-bd94-fb03f99e52f3)
Although I wouldn't worry too much about it, as it's your theme and more of an issue with the plugin. 


With the removed separate guild panel, the server bar no longer transitions into the window bar, due to added vignette on the top and bottom of the server bar.   
![image](https://github.com/refact0r/midnight-discord/assets/142122782/405f740a-743a-46d1-b189-88bc30cef005)
It does however, fix the overlapping UI elements caused by the separate server panel. 
![image](https://github.com/refact0r/midnight-discord/assets/142122782/12994a21-460c-4e56-9286-076d5a74daf1)

**Comment by SuperIronMan987** [comment]
cant tell if this is intentional or not but the size is inconsistent so id assume it isnt
![image](https://github.com/refact0r/midnight-discord/assets/70151481/2e22e8cd-2a04-493d-b2c0-a2887a5bbd11)

**Comment by refact0r** [comment]
> cant tell if this is intentional or not but the size is inconsistent so id assume it isnt ![image](https://user-images.githubusercontent.com/70151481/278837523-2e22e8cd-2a04-493d-b2c0-a2887a5bbd11.png)

I was playing around with some css snippets, and accidentally included it in the theme. I'll remove it.

**Comment by refact0r** [comment]
> cant tell if this is intentional or not but the size is inconsistent so id assume it isnt ![image](https://user-images.githubusercontent.com/70151481/278837523-2e22e8cd-2a04-493d-b2c0-a2887a5bbd11.png)

fixed

**Comment by refact0r** [comment]
4, 5, 6, 7, 11 fixed.

**Comment by refact0r** [comment]
@makimwah I will be keeping the separate server list for now, but if you hate it you can remove this section:

![image](https://github.com/refact0r/midnight-discord/assets/34758569/73f6a016-d547-42a2-94b9-be24df86b890)

like the comments say, make sure to uncomment the very bottom part to revert the folder colors.

**Comment by refact0r** [comment]
closing this issue because everything else brought up here their own issues
