### ISSUE TITLE
Betterfolder sidebar misplaced

### ISSUE THREAD

**Issue by blindmodz** [refact0r/midnight-discord#36]
When i use BetterFolders plugin, the sidebar goes under chat/server screen.
![image](https://github.com/refact0r/midnight-discord/assets/22939330/f9669343-666e-40f9-a2ff-25c9ce473245) Midnight theme

![image](https://github.com/refact0r/midnight-discord/assets/22939330/d82ec661-db15-431d-b0ee-94dffb9e1c52) Vanilla

**Comment by SuperIronMan987** [comment]
I think this is because of the new style where the server list has a background panel

**Comment by refact0r** [comment]
I have pushed a temporary fix. Just to verify, this is on vencord right?

**Comment by blindmodz** [comment]
> I have pushed a temporary fix. Just to verify, this is on vencord right?

sorry for the late reply. Yes, Vencord and after your push was fixed :D

**Comment by refact0r** [comment]
last issue!
