### ISSUE TITLE
New moon in-app icon cuts out Nitro in-app icons. 

### ISSUE THREAD

**Issue by makimwah** [refact0r/midnight-discord#37]
![image](https://github.com/refact0r/midnight-discord/assets/142122782/3ece530a-4e2f-4346-aecf-e3137749066b)

**Comment by refact0r** [comment]
well crap, i don't have nitro sooo...

could you inspect element and send a screenshot of the html tree?

**Comment by refact0r** [comment]
also, would you rather keep the nitro icon or the moon? it might be possible to only show the moon on the default discord icon.

**Comment by makimwah** [comment]
> well crap, i don't have nitro sooo...
> 
> could you inspect element and send a screenshot of the html tree?

I'm no developer at all so this might not even be what you need. 
![image](https://github.com/refact0r/midnight-discord/assets/142122782/76e4fe85-cad0-4985-ba85-1743ae7490d9)
You can use the Nitro app-icons yourself without Nitro when enabling FakeNitro in Vencord's plugin tab.

**Comment by makimwah** [comment]
> also, would you rather keep the nitro icon or the moon? it might be possible to only show the moon on the default discord icon.

I don't like the moon at all so I'd rather just stick with the Nitro icons. Not to mention that I'd probably use them anyway to feel less embarrassed about spending 10€ a month for Discord.

**Comment by refact0r** [comment]
i pushed a fix (using the preview nitro icon), please verify it works.

**Comment by makimwah** [comment]
> i pushed a fix (using the preview nitro icon), please verify it works.

Yep, works just fine. Thanks. 
![image](https://github.com/refact0r/midnight-discord/assets/142122782/ba3be615-688c-4d20-ab82-6be72effb013)
