### ISSUE TITLE
Billing isn't themed. 

### ISSUE THREAD

**Issue by makimwah** [refact0r/midnight-discord#38]
The smallest issue I found yet that has basically no relevance, but I thought I'd let you know anyway. 
![image](https://github.com/refact0r/midnight-discord/assets/142122782/e0ecc074-72b6-421c-826b-ae5a6e2edf2e)

**Comment by refact0r** [comment]
discord making 1000 color variables and then proceeding to manually set colors into multiple parts of their app:

**Comment by refact0r** [comment]
fixed, i won't bother changing the font color
