### ISSUE TITLE
"Explore discoverable servers" button when adding friends is unthemed. 

### ISSUE THREAD

**Issue by makimwah** [refact0r/midnight-discord#39]
Another small issue of something that isn't themed. Hopefully, I don't appear as if I'm nitpicking (although I am a little). 
![image](https://github.com/refact0r/midnight-discord/assets/142122782/821b1b10-b0a0-41b7-b1ac-59b881f93248)

**Comment by refact0r** [comment]
the green icon is an image, so I didn't have an easy way to theme it. it's probably possible to do a hue-rotate filter on it though.

**Comment by refact0r** [comment]
fixed
