### ISSUE TITLE
Colour does not apply correctly to online icon in options

### ISSUE THREAD

**Issue by SuperIronMan987** [refact0r/midnight-discord#44]
in the profile options it looks like this
![image](https://github.com/refact0r/midnight-discord/assets/70151481/b4ad36de-fb36-483c-b7f1-598f8337b8f0)
but renders correctly everywhere else (using the css shown below)
`--online-indicator: #23a55a;`

**Comment by SuperIronMan987** [comment]
![image](https://github.com/refact0r/midnight-discord/assets/70151481/a462f826-b918-446f-81ee-e1e67a5e85b2)
Still doesnt apply correctly, now all of the icons are green

**Comment by refact0r** [comment]
Latest update should fix this part, please check.

**Comment by draunger** [comment]
Assign me

**Comment by refact0r** [comment]
what? i fixed the issue already
