### ISSUE TITLE
member list gradient thing bug

### ISSUE THREAD

**Issue by Dev-Egor** [refact0r/midnight-discord#47]
![image](https://github.com/refact0r/midnight-discord/assets/90320659/044a0d2f-544d-4d12-a15e-4bd700c02ed4)
![image](https://github.com/refact0r/midnight-discord/assets/90320659/d6b46c51-8eb8-4fef-8aa5-4564e418ddc9)

the black gradient at the bottom of members list scrolls with the list instead of staying locked to the bottom

**Comment by refact0r** [comment]
fixed [1de5510](https://github.com/refact0r/midnight-discord/commit/1de5510f9c25fcdf4b1a576696f221b1281c081f)
