### ISSUE TITLE
Embed borders are distracting

### ISSUE THREAD

**Issue by bingbingyahoo27** [refact0r/midnight-discord#48]
Recently, a change was made to give embeds a pixel border. However, the UI design clashes with the rest of the theme in the following ways:

- The pixel border is too bright, which harshly contrasts with the background. It is very distracting!
    - A YouTube embed now looks much more alarming than it should, because of the bright red embed color that envelops the embedded content. This also makes it harder to focus on the thumbnail, or the content within the embed.
    - A plain blue link embed invokes the feeling of the embed itself having been "selected", in a way.
    - However, plain embeds (with no color) look beautiful as they are. But that's because there is no distracting color surrounding the embed in the first place.

I see what you were going for by making this change, but I think it needs some work. Is there a way you could make only the top of the embed red, or maybe the left side, but still make it look elegant?

What if you messed around with rounded corners? My idea would be, make the top of the embed colored, but keep the top corners sharp, and the bottom ones round.

![new-midnight-embed](https://github.com/refact0r/midnight-discord/assets/101210924/4b741bd5-d742-4947-a674-8c3899c3f0a7)
![image](https://github.com/refact0r/midnight-discord/assets/101210924/a0291636-c630-491b-8644-64132fc5e590)

Compare this to the default theme:

![image](https://github.com/refact0r/midnight-discord/assets/101210924/0b040038-450b-46a6-b523-aa0baec4e7a5)

EDIT: Whoops, haha, sorry about that old issue title. I still think it's a good start.

**Comment by bingbingyahoo27** [comment]
I should also mention, just for clarification: I am using the [Old Discord Font theme](https://raw.githubusercontent.com/Overimagine1/old-discord-font/main/source.css) on top of Midnight.

**Comment by refact0r** [comment]
i personally liked it a bit more but you make some good points.

**Comment by dotargz** [comment]
you should make a toggle for it! :D

**Comment by refact0r** [comment]
unfortunately i don't think i can make it toggle between the left edge border and the full border with a variable.
