### ISSUE TITLE
Corners no longer round

### ISSUE THREAD

**Issue by rauenzi** [refact0r/midnight-discord#5]
![image](https://user-images.githubusercontent.com/6865942/208231625-9a060c7d-daad-4153-a3e1-ab697924a098.png)

Corners no longer rounded on the channel list section

**Comment by refact0r** [comment]
Should be fixed by https://github.com/refact0r/midnight-discord/commit/2d98ffe19cf78e7d70a0cd5100d350bc661b8355.
