### ISSUE TITLE
This is literally the best discord theme

### ISSUE THREAD

**Issue by BinaryQuantumSoul** [refact0r/midnight-discord#53]
Hello,
I tried all the themes from BetterDiscord and this one is the best because it adds a cool UI, but is really similar to native experience. 

Few suggestions:
- I did have to put normal text to brighter colors since it was to close to background color and therefore hard to read
```css
/* text colors */
--text-1: hsl(220, 40%, 95%); /* bright text on colored elements */
--text-2: hsl(220, 32%, 82%); /* headings and important text */
--text-3: hsl(220, 25%, 70%); /* normal text */
--text-4: hsl(220, 15%, 40%); /* icon buttons and channels */
--text-5: hsl(220, 15%, 25%); /* muted channels/chats and timestamps */
```
- I also had to change animation speed because it looked too slow when quickly hovering. I found 0.05s to be the best
```css
/* animations */
--hover-push: 0.05s ease; /* channels/members when hovered */
```
- I would suggest declining the different accents gradient from a common hue so that it's easy to change the accent color throughout the theme
```css
/* accent colors */
--base-hue: 190; /* set the base hue */

--accent-1: hsl(var(--base-hue), 80%, 60%); /* links */
--accent-2: hsl(var(--base-hue), 80%, 48%); /* general unread/mention elements */
--accent-3: hsl(var(--base-hue), 80%, 42%); /* accent buttons */
--accent-4: hsl(var(--base-hue), 80%, 36%); /* accent buttons when hovered */
--accent-5: hsl(var(--base-hue), 80%, 30%); /* accent buttons when clicked */
--mention: hsla(var(--base-hue), 80%, 52%, 0.1); /* mentions & mention messages */
--mention-hover: hsla(var(--base-hue), 80%, 52%, 0.05); /* mentions & mention messages when hovered */
```

**Comment by refact0r** [comment]
Thanks. 

The original vision for the theme was to have a dark, low contrast colorscheme that is easy to use at night. I understand it may be harder to read depending on your display but I will keep the same text colors.

Personally I don't think 0.2s is very slow for an animation. It is intended to look fluid.

I considered adding hue variables but I don't think it's worth it. If you wanted to vary the hue (hsl is not a perfect color system) you would have to undo the variable.

**Comment by BinaryQuantumSoul** [comment]
No probs,
Those were opiniated suggestions anyway.

By the way, I made a plugin just for animating the hue for your theme (using my proposed accent colors definitions)
https://github.com/BinaryQuantumSoul/DiscordAccentColorRolling
