### ISSUE TITLE
Weird User Profule

### ISSUE THREAD

**Issue by Soap-0020** [refact0r/midnight-discord#54]
![image](https://github.com/refact0r/midnight-discord/assets/110540103/5cdbb8b9-7840-450a-9f0e-b98b1c1f7493)
should be lighter where the buttons are

**Comment by refact0r** [comment]
how do i get to this?

**Comment by Soap-0020** [comment]
press view profile on a user

**Comment by refact0r** [comment]
this is what i see
![image](https://github.com/refact0r/midnight-discord/assets/34758569/135476b6-53bb-49d5-862e-8a588485887d)

**Comment by Soap-0020** [comment]
weird, i see it like how i showed, not sure how to fix it

**Comment by refact0r** [comment]
have you customized the theme at all? also make sure you have the most updated version.
