### ISSUE TITLE
Music Player 

### ISSUE THREAD

**Issue by ShalokShalom** [refact0r/midnight-discord#6]
Hi :)

Could you say me, how I can get this music player into my Discord?

![Screenshot_66](https://user-images.githubusercontent.com/6344099/217926392-9c03f14d-66f3-4be5-93ef-c39975643ef2.png)

**Comment by refact0r** [comment]
It is a plugin called SpotifyControls. I'm using Vencord, but Betterdiscord has it too.

**Comment by ShalokShalom** [comment]
Thanks a lot!
