### ISSUE TITLE
Rounded corners in fullscreened image hides the rest.

### ISSUE THREAD

**Issue by ThatLadLegend** [refact0r/midnight-discord#68]
When using this theme I have encountered an issue where the corners of an image will be so aggressive, I cannot see the full image and only half. This is worse for smaller images.

![DiscordCanary_GRpwKqFgK8](https://github.com/refact0r/midnight-discord/assets/39273354/1849a118-9585-49b4-a820-6d2b55e5ff41)
![DiscordCanary_9tAnOeVZJt](https://github.com/refact0r/midnight-discord/assets/39273354/03a60c3b-995c-4859-bb57-1b1f4be76a05)

**Comment by LostQuasar** [comment]
Can confirm this issue
