### ISSUE TITLE
Midnight theme buggin

### ISSUE THREAD

**Issue by Keler69** [refact0r/midnight-discord#7]
Midnight theme is broken, colors aren't where they are supposed to be
![image](https://user-images.githubusercontent.com/110538492/219552042-317dcea2-7bf0-40bc-96ba-56f1e9e8849e.png)
![image](https://user-images.githubusercontent.com/110538492/219552144-43a25486-e8b8-4450-a084-754df07503e2.png)

**Comment by Beancoded** [comment]
> Midnight theme is broken, colors aren't where they are supposed to be ![image](https://user-images.githubusercontent.com/110538492/219552042-317dcea2-7bf0-40bc-96ba-56f1e9e8849e.png) ![image](https://user-images.githubusercontent.com/110538492/219552144-43a25486-e8b8-4450-a084-754df07503e2.png)
i have the same problem

**Comment by refact0r** [comment]
man i hate discord

fix coming soon

**Comment by ZEpsilonZ** [comment]
It is still broken.
![Capture3](https://user-images.githubusercontent.com/125721196/219843638-4f1bcd04-d0b1-493f-b650-f4b9d731be33.PNG)
![Capture2](https://user-images.githubusercontent.com/125721196/219843642-690deb10-5665-4c70-854d-5a9e3ecfd859.PNG)
![Capture](https://user-images.githubusercontent.com/125721196/219843643-6946d3e2-4a0d-4530-b589-c1d949fccdb8.PNG)
I also updated it already.

**Comment by Keler69** [comment]
> @Keler69 @Beancoded i have pushed an update, please reply to verify it works

still broken, same with @Beancoded

**Comment by Beancoded** [comment]
yup i updated and its still broken, why does discord do this..

**Comment by refact0r** [comment]
It works for me now, please try again. Seems like github was having api issues yesterday so the fixed version was not distributed.

**Comment by ZEpsilonZ** [comment]
Thanks so much, refact0r! It works fine now.

**Comment by Keler69** [comment]
> It works for me now, please try again. Seems like github was having api issues yesterday so the fixed version was not distributed.

It works now. Thanks, U a real one
