### ISSUE TITLE
Reply alignment issue

### ISSUE THREAD

**Issue by viledissociation** [refact0r/midnight-discord#70]
First of all thank you for making this wonderful theme, I found an issue with the alignment after I screwed around with the colors a bit..
![image](https://github.com/refact0r/midnight-discord/assets/85312115/445a44a1-a509-4f51-ae1e-98dfc18ebf7d)
I was wondering if this was just me or if this is a bug, but when someone replies to me, those replies seem to be moved a little to the right. this issue is only on the left side of the message, the right is perfectly aligned. Thank you in advance

**Comment by refact0r** [comment]
this isn't an alignment issue, there's supposed to be a colored bar with the `--accent-3` color on the left side of messages that mention/reply you. 
![image](https://github.com/refact0r/midnight-discord/assets/34758569/5041cbf0-1ce1-4c4f-8417-b3c43db9a3e3)
but it looks like you set `--accent-3` to be the same color as `--bg-3`, so it looks weird.

**Comment by viledissociation** [comment]
oh okay thank you so much
