### ISSUE TITLE
New Discord update has gotten rid of roundness

### ISSUE THREAD

**Issue by benwaghorn** [refact0r/midnight-discord#73]
Opened up Discord this morning to see the theme has lost its roundness in multiple areas across the app (members list, friends list, DMs, channel shadows, etc). Could be the result of a Discord client update, tested on both Stable and Canary clients with the same results. 

![image](https://github.com/refact0r/midnight-discord/assets/56948009/aaaaaf19-00a2-4db0-bf7d-389a7f83838a)

**Comment by yukalele** [comment]
im having this issue as well!

**Comment by ashley-graves** [comment]
It's an issue with the new Discord update, most class names have been re-scrambled.
Just stay patient & wait for refact0r to update the selectors.

**Comment by refact0r** [comment]
seems to be reverted on stable

**Comment by benwaghorn** [comment]
Reinstalling Vencord seems to have fixed it for me on stable, even though I updated this morning.
