### ISSUE TITLE
view server as role popup

### ISSUE THREAD

**Issue by barraIhsan** [refact0r/midnight-discord#74]
It currently got cut out when using the theme
Vanilla:
![image](https://github.com/refact0r/midnight-discord/assets/57800056/04da03ca-d90a-4898-87c0-a46d021a3195)

Midnight:
![image](https://github.com/refact0r/midnight-discord/assets/57800056/4e94ad2a-b88e-4640-8af9-3746bc8a9cb3)

The css class is `viewAsRolesWarning__4bb09` (idk about discord theming, but I assume the last 5 letter is added by react?)

**Comment by refact0r** [comment]
how do you get this again? all i see is a bar at the top

**Comment by barraIhsan** [comment]
> how do you get this again? all i see is a bar at the top

Go to server settings > Roles > Right click on any roles > View Server As Role > Join A VC

**Comment by barraIhsan** [comment]
https://github.com/refact0r/midnight-discord/assets/57800056/8d52307e-b2ca-41dd-9dde-f70ab1abe654

This is the video of how to reproduce this bug
