### ISSUE TITLE
Mod View Red Text?

### ISSUE THREAD

**Issue by barraIhsan** [refact0r/midnight-discord#75]
If you go to `Mod View` and then clicking on the `Mod Permissions` the text would be in full red?
<details><summary>Vanilla:</summary>

![image](https://github.com/refact0r/midnight-discord/assets/57800056/6b9635a7-a045-4cce-b04d-d57f912aee1c)

</details>
<details><summary>Midnight:</summary>

![image](https://github.com/refact0r/midnight-discord/assets/57800056/be4a8a8f-0c21-457b-a90f-8300d2062d4d)

</details>

I found 2 classes, 
the first is `permissionItemHeader__327be > permissionTitle_ffc8c2 > text-xs-normal__56c35` (`--header-muted` by default)
the second is  `permissionItemDescription__284c1 > text-sm-normal_e612c7` (`--text-secondary` by default)

Idk why you set most of the variable to red in the css file
[Jump ↗](https://github.com/refact0r/midnight-discord/blob/master/midnight.css#L1097-L1098)
```css
--text-primary: red;
--text-secondary: red;
```
[Jump ↗](https://github.com/refact0r/midnight-discord/blob/master/midnight.css#L955)
```css
--header-muted: red;
```

**Comment by refact0r** [comment]
> Idk why you set most of the variable to red in the css file

I set things to red when I don't know where they are so it's easier to find them. Thanks for pointing this one out.
