### ISSUE TITLE
Color change for the status indicators

### ISSUE THREAD

**Issue by FAKHORII** [refact0r/midnight-discord#80]
the status indicator (Online, Idle...etc) colors for catppuccin (mocha mauve) are a bit pale and hurt the eye in a way,
would be much better if the colors were a bit more vibrant, it would still match the theme still, even better in my opinion
and thank you <3

**Comment by refact0r** [comment]
those colors are from the official catppuccin theme.
if you don't like them you

**Comment by FAKHORII** [comment]
ah ofc, why would u change just for me, and who's gonna ask anyway, I can't change them locally, I'm using Vencord
the problem with those colors, that yellow and green are very pale and look alike almost..  I just thought a tiny bit of vibrance would make it better, surely nobody will complain lol
thanks anyway <3

**Comment by refact0r** [comment]
if you're using vencord, you can download and use the theme file and change the variables in it (or copy it into quickcss).

**Comment by FAKHORII** [comment]
I would love to do it but I am sorry, I don't know how to do any of it, thanks for replying to me again, I appreciate ur time

**Comment by FAKHORII** [comment]
ooops, nvm, It's super easy it seems, I went looking around and it takes no time lol, much appreciated...thank u sir <3
