### ISSUE TITLE
Discord UI Updates

### ISSUE THREAD

**Issue by barraIhsan** [refact0r/midnight-discord#81]
I don't know what they're updating, but I noticed some thing breaks, like the midnight icon, the member list color, etc.
For example midnight icon, the react random class is changed. From `childWrapper__01b9c` to `childWrapper_a6ce15`

![image](https://github.com/refact0r/midnight-discord/assets/57800056/1d122633-683a-4db6-8a11-678bcbc8dfcf)

**Comment by refact0r** [comment]
discord updated canary classes, use stable for now.
i'm not sure if they're going to push this one to stable, but if they do i will fix things.

**Comment by refact0r** [comment]
nevermind its on stable now :(

**Comment by refact0r** [comment]
seems to be reverted to the original for me on vesktop stable.

**Comment by refact0r** [comment]
for now, use https://github.com/refact0r/midnight-discord/blob/master/midnight-new.css

if you are using the `midnight.theme.css` file:
```css
replace
@import url('https://refact0r.github.io/midnight-discord/midnight.css');
with
@import url('https://refact0r.github.io/midnight-discord/midnight-new.css');
```

**Comment by Scarlaid** [comment]
It would be best to fix the default scrollbar too, the provided theme didn't do that.

![image](https://github.com/refact0r/midnight-discord/assets/90851437/5da1e9a1-787a-4af3-933b-1af1d022ec7b)
![Vesktop_zc9oeVYTps](https://github.com/refact0r/midnight-discord/assets/90851437/5ffb6540-70df-47e3-9e04-f0c395e2dd33)

**Comment by refact0r** [comment]
oh i fixed this but forgot to push lol

fixed 👍
