### ISSUE TITLE
Weird backgroud because of the role="tablist"

### ISSUE THREAD

**Issue by uynilo9** [refact0r/midnight-discord#89]
![image](https://github.com/refact0r/midnight-discord/assets/115794240/f54e3293-7aa4-441f-9001-b3f0cf308a60)
![image](https://github.com/refact0r/midnight-discord/assets/115794240/476099e8-62cf-49a4-874d-2adb2b021b1c)
![image](https://github.com/refact0r/midnight-discord/assets/115794240/57c32810-ccbc-42cd-81c1-1490fefb6e00)

**Comment by refact0r** [comment]
looks fine for me.

do you have any other themes enabled?

**Comment by uynilo9** [comment]
no i dont
![image](https://github.com/refact0r/midnight-discord/assets/115794240/3b108add-2348-4fce-b3e0-9ab4c3d2196d)

**Comment by Remco0o** [comment]
> no i dont ![image](https://private-user-images.githubusercontent.com/115794240/320192501-3b108add-2348-4fce-b3e0-9ab4c3d2196d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzOTI0NTAsIm5iZiI6MTcxMjM5MjE1MCwicGF0aCI6Ii8xMTU3OTQyNDAvMzIwMTkyNTAxLTNiMTA4YWRkLTIzNDgtNGZjZS1iM2UwLTlhYjRjM2QyMTk2ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNlQwODI5MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYzQzNjdmZDVlMmNkNTY3NTU2ZTIyNTI1YmFlNzY1ZTU3OWFlNWQyN2Q4NmQ4MmMxYTExMDRlNGM0YjY5YWQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bSH_xoSC3KaoG2aSj6w2WPnpcUgMdWM6f22EfI1YObM)

check also the online theme tab

**Comment by uynilo9** [comment]
ohhhh i found it
thanks <3
![image](https://github.com/refact0r/midnight-discord/assets/115794240/f17b7260-de5f-4440-8641-93ec7691bffc)
