### ISSUE TITLE
Incorrect margins in fullscreen voice channel

### ISSUE THREAD

**Issue by he3als** [refact0r/midnight-discord#9]
![image](https://user-images.githubusercontent.com/65787561/227744303-9f696a0f-8bc5-4430-9691-a9f2cdce5458.png)

**Comment by refact0r** [comment]
Fixed in https://github.com/refact0r/midnight-discord/commit/c22454f76144dd3399e8a259feb7f3b990dee081

**Comment by he3als** [comment]
This does fix the issue, but there is no rounded corners at the bottom of the fullscreen VC. I tried fixing this myself, but I haven't found a way to fix it. Regardless, it's much better than having no margin at the top.

![Discord_Ltk9vvzJLw](https://user-images.githubusercontent.com/65787561/227764114-b58b7a05-71eb-4f38-8ddd-e91e9a8709d6.png)

**Comment by refact0r** [comment]
I have pushed another fix, please check if it works this time

**Comment by he3als** [comment]
Fixed, thank you very much
