### ISSUE TITLE
biscuit logo doesn't show up on the direct messages button

### ISSUE THREAD

**Issue by notexactlynikhil** [refact0r/midnight-discord#90]
![image](https://github.com/refact0r/midnight-discord/assets/58302941/0a01c9c0-f4ad-4c25-8547-3737b93b9712)
the last time i used the biscuit theme was around a month back and it wa working perfectly fine. I tried getting it back today and this is what it looks like.

note: im not the only one facing the issue, it doesnt seem to work for my friends either

**Comment by refact0r** [comment]
should be fixed in https://github.com/refact0r/midnight-discord/commit/73e9bf9679e00ffeb389502ee5862c23a3e72966

**Comment by notexactlynikhil** [comment]
works now. thanks!
