### ISSUE TITLE
USRBG bad rounding

### ISSUE THREAD

**Issue by Dev-Egor** [refact0r/midnight-discord#97]
Theme causes USRBG plugin profile banners to have rounding at the top which doesn't match the rounding of the profile border, looks bad.
![image](https://github.com/refact0r/midnight-discord/assets/90320659/9848a690-4ca1-41e6-a9d0-20eed3a6e691)
![image](https://github.com/refact0r/midnight-discord/assets/90320659/656d6e10-955c-4c6f-8893-e6994c7450b9)
![image](https://github.com/refact0r/midnight-discord/assets/90320659/7874faf3-f876-4ef9-a06b-ba01bd87d5f3)

**Comment by refact0r** [comment]
can you check if this is still an issue?
